#version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: saas-platform-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: saas_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: saas-platform-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    container_name: saas-platform-redis
    ports:
      - "6379:6379"
    restart: always

  identity-service:
    build:
      context: .
      dockerfile: apps/services/identity/Dockerfile
    container_name: saas-platform-identity
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=saas_identity;Username=postgres;Password=postgrespassword
      - RabbitMQ__Host=rabbitmq
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
      - rabbitmq
    restart: always

  gateway-service:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: saas-platform-gateway
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__identity-cluster__Destinations__destination1__Address=http://identity-service:8080
      - ReverseProxy__Clusters__tenant-cluster__Destinations__destination1__Address=http://tenant-service:8080
      - ReverseProxy__Clusters__billing-cluster__Destinations__destination1__Address=http://billing-service:8080
    depends_on:
      - identity-service
    restart: always

  billing-service:
    build:
      context: .
      dockerfile: apps/services/billing/Dockerfile
    container_name: saas-platform-billing
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=saas_billing;Username=postgres;Password=postgrespassword
      - RabbitMQ__Host=rabbitmq
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - Paddle__WebhookSecret=paddle_secret_test_123
    depends_on:
      - db
      - rabbitmq
    restart: always

volumes:
  postgres_data:
  rabbitmq_data:
